<?php

namespace Database\Seeders;

use App\Models\Equipment;
use App\Models\EquipmentType;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EquipmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            'Interiør' => [
                'Kørecomputer',
                'Digitalt cockpit',
                'Bagagerumsdækken',
                'Dobbelt bagagerumsbund',
                'Akustikglas i for',
                'Akustikglas i bag',
                'Multifunktionsrat',
                'Læderrat',
                'Interiør, stof',
                'Læderindtræk',
                'Dellæderindtræk',
                'Kunstlæderindtræk',
                'Delkunstlæderindtræk',
                'Alcantaraindtræk',
                'Delalcantaraindtræk',
                'Sportssæder',
                'Pilotsæder',
                'Højdejust. førersæde',
                'El indst. forsæder',
                'El indst. førersæde',
                'El indst. førersæde m. memory',
                'Justerbar lændestøtte',
                'El-justerbar lændestøtte',
                'El komfortsæder',
                'Massage i førersæde',
                'Massage i forsæder',
                'Splitbagsæde',
                'Integrerede børnesæder',
                '3 individuelle sæder i bag',
                'Integrerede rullegardiner',
                '6 personers',
                '7 personers',
                'Mørk loftbeklædning',
                'Ambiente belysning',
            ],
            'Eksteriør' => [
                'Alufælge',
                '15 tommer Alufælge',
                '16 tommer Alufælge',
                '17 tommer Alufælge',
                '18 tommer Alufælge',
                '19 tommer Alufælge',
                '20 tommer Alufælge',
                '21 tommer Alufælge',
                '22 tommer Alufælge',
                'Vinterhjul',
                'Helårshjul',
                'Soltag',
                'El-soltag',
                'Panoramatag',
                'El-sidespejle',
                'El-sidespejle m. varme',
                'El-klapbare sidespejle',
                'El-klapbare sidespejle m. varme',
                'Virtuelle sidespejle',
                'Tågelygter',
                'Bi-xenon',
                'Xenonlygter',
                'LED Kørelys',
                'Fuld LED forlygter',
                'Kurvelys',
                'Adaptive forlygter',
                'Matrix LED forlygter',
                'Laser forlygter',
                'LED baglygter',
                'Dynamisk blinklys',
                'Dynamisk blinklys i bag',
                'Tagræling',
                'Mørktonede ruder i bag',
                'Aftageligt træk',
                'Solceller',
                'Områdebelysning',
            ],
            'Sikkerhed & førerassistance' => [
                'Alarm',
                'Regnsensor',
                'Auto. parkering',
                'Semi-automatisk parkeringssystem',
                '360° kamera',
                'Bakkamera',
                'Virtuelt bakspejl',
                'Parkeringssensor (bag)',
                'Parkeringssensor (for)',
                'Trafikkamera',
                'Videoovervågning',
                'Dæktryksmåler',
                'Træthedsregistrering',
                'Førerovervågning med advarsel',
                'Skiltegenkendelse',
                'Intelligent hastighedsassistent',
                'Nightvision',
                'Isofix',
                'Lygtevasker',
                'Automatisk lys',
                'Fjernlysassistent',
                'Airbags',
                'Db. airbags',
                '4 airbags',
                '6 airbags',
                '7 airbags',
                '8 airbags',
                '9 airbags',
                '10 airbags',
                'Antispin',
                'ESP / ESC',
                'City steering',
                'Vognbaneassistent',
                'Blindvinkelassistent',
                'Auto. nødbremse',
                'Stemmebetjening',
                'Auto hold',
                'EDR-boks',
                'Automatisk nødassistent',
            ],
            'Klima & Komfort' => [
                'Automatgear',
                'Ratgearskifte',
                'Varme i rat',
                'Aircondition',
                'Fuldaut. klima',
                '2 zone klima',
                '3 zone klima',
                '4 zone klima',
                'Køl i handskerum',
                'Elektrisk kabinevarmer',
                'Motorkabinevarmer',
                'Varmepumpe',
                'Centrallås',
                'Fjernb. centrallås',
                'Nøglefri adgang',
                'Nøglefri tænding',
                'Fartpilot',
                'Adaptiv fartpilot',
                'Adaptiv fartpilot med kø-assistent',
                'Varme i forrude',
                'Aut. nedbl. bakspejl',
                'Udv. temp. måler',
                'Sædekøling',
                'Sædevarme',
                'Varme i bagsæde',
                'Varme i 3. sæderække',
                'El-ruder',
                '4x el-ruder',
                'Automatisk start/stop',
                'El betjente døre',
                'El betjent frontklap',
                'El betjent bagklap',
                'Fod betjent bagklap',
                'Frunk',
                'Adaptiv undervogn',
                'Luftundervogn',
                'Elektrisk parkeringsbremse',
                'Head-up display',
                'Trådløs mobilopladning',
                'V2L',
                'V2G',
                'Manuel forvarmning af batteri',
                'Automatisk forvarmning af batteri',
                'Integreret ladekabel',
                'Type-2 ladekabel',
                'Nødlader',
                'App integration',
            ],
            'Infotainment & navigation' => [
                'CD afspiller',
                'CD/radio',
                'DAB radio',
                'DAB+ Radio',
                'Navigation',
                'Håndfrit til mobil',
                'Musikstreaming via bluetooth',
                'Android auto',
                'Apple carplay',
                'Internet',
                'SD kortlæser',
                'USB A tilslutning',
                'USB C tilslutning',
                'AUX tilslutning',
                'Bagsæde underholdningssystem',
            ],
        ];

        DB::transaction(function () use ($data) {
            foreach ($data as $typeName => $equipmentNames) {
                $type = EquipmentType::firstOrCreateInsensitive(['name' => $typeName]);

                foreach ($equipmentNames as $name) {
                    Equipment::firstOrCreateInsensitive(
                        [
                            'name' => $name,
                            'equipment_type_id' => $type->id,
                        ]
                    );
                }
            }
        });
    }
}
